name: Build main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and test
        run: ./gradlew clean build
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          include_passed: true
          report_paths: '**/build/test-results/test/TEST-*.xml'
